# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='gradyear',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='last_name',
            field=models.CharField(default='last', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='nickname',
            field=models.CharField(default='joker', max_length=64),
            preserve_default=False,
        ),
    ]
