# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_auto_20161107_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='nickname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
