# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_auto_20161107_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='gradyear',
            field=models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)]),
        ),
    ]
