# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='location',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
